new Rotor("R1Z", "Z");
new SolidLG(0, 1, 1);
new Rotor("R2Y", "Y");
new SolidLG(0, -1, -1);
new SolidLG(0, -2, 0);
new Piston("P1Z", "-Y");
new SolidLG(0, 0, 2);
new Piston("P2Z", "Z");
new SolidLG(0, 1, 1);
new Rotor("R3-Y", "Y");
new SolidLG(0, 0, 1);
new SolidLG(-2, 0, 0);
new Piston("P3X", "-X");
new SolidLG(0, 0, 2);
new Piston("P4X", "Z");
new SolidLG(0, 0, 1);
new Rotor("R4X", "Z");
new SolidLG(1, 0, 1);
new Rotor("R5Y", "X");
new SolidLG(0, -1, 1);
new Rotor("R6-Z", "-Y");